modules:
  - name: "Introduction"
    lessons:
      - name: "About the Study"
        file: "00-intro/about.md"
        shortName: "about"
      - name: "Consent"
        file: "00-intro/consent.md"
        shortName: "consent"
  - name: "Pre-Survey"
    lessons:
      - name: "Demographics"
        file: "01-pre-survey/demographics.md"
        shortName: "demographics"
      - name: "Background"
        file: "01-pre-survey/background.md"
        shortName: "background"
      - name: "Attitudes"
        file: "01-pre-survey/attitudes.md"
        shortName: "attitudes"
  - name: "Lesson"
    lessons:
      - name: "Condition Training"
        file: "02-lesson/condition-training.md"
        shortName: "condition-training"
      - name: "Practice Trial I" 
        file: "02-lesson/practice-easy.md"
        shortName: "practice-easy"
      - name: "Practice Trial II"
        file: "02-lesson/practice-hard.md"
        shortName: "practice-hard"
      - name: "Lesson Summary"
        file: "02-lesson/lesson-summary.md"
        shortName: "lesson-summary"
  - name: "Persistence Task" 
    lessons: 
      - name: "Task 1" 
        file: "03-persistence-task/task-1.md"
        shortName: "task-1"
      - name: "Task 2" 
        file: "03-persistence-task/task-2.md"
        shortName: "task-2"
      - name: "Task 3" 
        file: "03-persistence-task/task-3.md"
        shortName: "task-3"
   - name: "Post-Survey"
     lessons: 
       - name: "Perceptions" 
         file: "04-post-survey/perceptions.md"
         shortName: "perceptions"
       - name: "Follow-up" 
         file: "post-survey/follow-up.md"
         shortName: "follow-up"
       - name: "Thank You" 
         file: "04-post-survey/thank-you.md"
         shortName: "thank-you"
         
        
