modules:
  - name: "Click here to start the study"
    lessons:
      - name: "Getting Started"
        file: "00-getting-started.md"
        shortName: "about"
      - name: "Consent"
        file: "01-consent.md"
        shortName: "consent"
      - name: "Pre-Survey"
        file: "02-pre-questionnaire.md"
        shortName: "pre-survey"
      - name: "Instructions"
        file: "03-instructions.md"
        shortName: "instructions"
      - name: "Lesson 1: Operators"
        file: "04-lesson-1-operators.md"
        shortName: "lesson-1"
      - name: "Lesson 2: Variables"
        file: "05-lesson-2-variables.md"
        shortName: "lesson-2"
      - name: "Lesson 3: Vectors and Functions"
        file: "06-lesson-3-vectors-and-functions.md"
        shortName: "lesson-3"
      - name: "Lesson 4: Data Frames and More Functions"
        file: "07-lesson-4-data-frames.md"
        shortName: "lesson-4"
      - name: "Lesson Summary"
        file: "08-lesson-summary.md"
        shortName: "lesson-summary"
      - name: "Landing 1"
        file: "09-landing-1.md"
        shortName: "landing-1"
      - name: "Extra 1"
        file: "10-extra-1.md"
        shortName: "extra-1"
      - name: "Landing 2"
        file: "11-landing-2.md"
        shortName: "landing-2"
      - name: "Extra 2"
        file: "12-extra-2.md"
        shortName: "extra-2"
      - name: "Landing 3"
        file: "13-landing-3.md"
        shortName: "landing-3"
