modules: 
     - name: "Click Here to Start the Study"
       lessons:
            - name: "Getting Started"
              file: "00-getting-started.md"
              shortName: "about"
            - name: "Consent"
              file: "01-consent.md"
              shortName: "consent"
            - name: "Pre-Survey"
              file: "02-pre-questionnaire.md"
              shortName: "pre-survey"
            - name: "Instructions"
              file: "03-instructions.md"
              shortName: "instructions"
            - name: "Lesson Part I"
              file: "04-lesson-part-1.md"
              shortName: "lesson-easy"
            - name: "Lesson Part II"
              file: "05-lesson-part-2.md"
              shortName: "lesson-hard"
            - name: "Lesson Summary"
              file: "06-lesson-summary.md"
              shortName: "lesson-summary"
    
